# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [
  "README.md",
  "gulpfile.js",
  "package.json",
  "node_modules",
  ".bowerrc",
  ".jshintrc"
]
highlighter: pygments

# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Powerful Fleet Management System
name: UMAPS
tagline:
author :
  name : gpshandle.com
  email : vu@umaps.vn
  github : duvu
  twitter : duvu
  feedburner : duvu

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://duvu.github.io
